.TH "Assistance" 3 "Vendredi 8 Mai 2015" "Version 1.2.2" "Locker_Control" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Assistance \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <assistance\&.h>\fP
.PP
Est dérivée de QWidget\&.
.SS "Fonctions membres publiques"

.in +1c
.ti -1c
.RI "\fBAssistance\fP (QWidget *parent=0)"
.br
.ti -1c
.RI "\fB~Assistance\fP ()"
.br
.in -1c
.SH "Documentation des constructeurs et destructeur"
.PP 
.SS "Assistance::Assistance (QWidget * parent = \fC0\fP)\fC [explicit]\fP"

.SS "Assistance::~Assistance ()"


.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Locker_Control à partir du code source\&.
