.TH "S:/QT_CREATOR/Locker_Control/boxchoice.cpp" 3 "Vendredi 8 Mai 2015" "Version 1.2.2" "Locker_Control" \" -*- nroff -*-
.ad l
.nh
.SH NAME
S:/QT_CREATOR/Locker_Control/boxchoice.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'boxchoice\&.h'\fP
.br
\fC#include 'ui_boxchoice\&.h'\fP
.br
\fC#include <QDebug>\fP
.br
\fC#include <QGraphicsTextItem>\fP
.br
\fC#include <QToolTip>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBHEIGHT\fP   100"
.br
.ti -1c
.RI "#define \fBWIDTH\fP   100"
.br
.ti -1c
.RI "#define \fBSTARTX\fP   0"
.br
.ti -1c
.RI "#define \fBSTARTY\fP   0"
.br
.in -1c
.SH "Documentation des macros"
.PP 
.SS "#define HEIGHT   100"

.SS "#define STARTX   0"

.SS "#define STARTY   0"

.SS "#define WIDTH   100"

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Locker_Control à partir du code source\&.
