.TH "BoxChoice" 3 "Vendredi 8 Mai 2015" "Version 1.2.2" "Locker_Control" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BoxChoice \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <boxchoice\&.h>\fP
.PP
Est dérivée de QWidget\&.
.SS "Connecteurs publics"

.in +1c
.ti -1c
.RI "void \fBValidBox\fP ()"
.br
.ti -1c
.RI "void \fBCancel\fP ()"
.br
.ti -1c
.RI "void \fBmanageRect\fP (int)"
.br
.ti -1c
.RI "void \fBRefresh\fP ()"
.br
.ti -1c
.RI "QList< int > \fBGetBoxSelected\fP ()"
.br
.in -1c
.SS "Signaux"

.in +1c
.ti -1c
.RI "void \fBSendListBoxSelected\fP (QList< int >)"
.br
.in -1c
.SS "Fonctions membres publiques"

.in +1c
.ti -1c
.RI "\fBBoxChoice\fP (\fBMenuDelivery\fP *WMenuDelivery, \fBCSQLite_Local_DB\fP *, QWidget *parent=0)"
.br
.ti -1c
.RI "\fB~BoxChoice\fP ()"
.br
.ti -1c
.RI "void \fBSetShowWidgets\fP (\fBShowWidgets\fP *TShowWidgets)"
.br
.ti -1c
.RI "QGraphicsView * \fBGetGraphicsView\fP ()"
.br
.ti -1c
.RI "QGraphicsScene * \fBGetScene\fP ()"
.br
.ti -1c
.RI "void \fBretranslateUi\fP ()"
.br
.ti -1c
.RI "void \fBmanageDoorUnvailable\fP (int id)"
.br
.ti -1c
.RI "void \fBmanageRectNoChecked\fP (int id)"
.br
.ti -1c
.RI "void \fBShowMessageError\fP (QString mesg)"
.br
.in -1c
.SH "Documentation des constructeurs et destructeur"
.PP 
.SS "BoxChoice::BoxChoice (\fBMenuDelivery\fP * WMenuDelivery, \fBCSQLite_Local_DB\fP * bd, QWidget * parent = \fC0\fP)\fC [explicit]\fP"

.SS "BoxChoice::~BoxChoice ()"

.SH "Documentation des fonctions membres"
.PP 
.SS "void BoxChoice::Cancel ()\fC [slot]\fP"

.SS "QList< int > BoxChoice::GetBoxSelected ()\fC [slot]\fP"

.SS "QGraphicsView * BoxChoice::GetGraphicsView ()"

.SS "QGraphicsScene * BoxChoice::GetScene ()"

.SS "void BoxChoice::manageDoorUnvailable (int id)"

.SS "void BoxChoice::manageRect (int id)\fC [slot]\fP"

.SS "void BoxChoice::manageRectNoChecked (int id)"

.SS "void BoxChoice::Refresh ()\fC [slot]\fP"

.SS "void BoxChoice::retranslateUi ()"

.SS "void BoxChoice::SendListBoxSelected (QList< int >)\fC [signal]\fP"

.SS "void BoxChoice::SetShowWidgets (\fBShowWidgets\fP * TShowWidgets)\fC [inline]\fP"

.SS "void BoxChoice::ShowMessageError (QString mesg)"

.SS "void BoxChoice::ValidBox ()\fC [slot]\fP"


.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Locker_Control à partir du code source\&.
