.TH "CDoors" 3 "Vendredi 8 Mai 2015" "Version 1.2.2" "Locker_Control" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CDoors \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <cdoors\&.h>\fP
.SS "Fonctions membres publiques"

.in +1c
.ti -1c
.RI "\fBCDoors\fP (\fBCSQLite_Local_DB\fP *BD)"
.br
.ti -1c
.RI "bool \fBOpenDoors\fP (QList< int > DoorsList)"
.br
.ti -1c
.RI "bool \fBCloseDoors\fP (QList< int > DoorsList)"
.br
.ti -1c
.RI "bool \fBLockDoors\fP (QList< int > DoorsList)"
.br
.ti -1c
.RI "bool \fBUnlockDoors\fP (QList< int > DoorsList)"
.br
.ti -1c
.RI "bool \fBOpenDoor\fP (int idDoor)"
.br
.ti -1c
.RI "bool \fBCloseDoor\fP (int idDoor)"
.br
.ti -1c
.RI "bool \fBLockDoor\fP (int idDoor)"
.br
.ti -1c
.RI "bool \fBUnlockDoor\fP (int idDoor)"
.br
.ti -1c
.RI "QList< \fBstruct_DoorsStatus\fP > \fBDoorsStatus\fP (QList< int > DoorsList)"
.br
.ti -1c
.RI "bool \fBDoorsIsClosed\fP (QList< int > DoorsList)"
.br
.ti -1c
.RI "\fBstruct_DoorsStatus\fP \fBDoorStatus\fP (int idDoor)"
.br
.ti -1c
.RI "bool \fBDoorIsClosed\fP (int idDoor)"
.br
.in -1c
.SH "Documentation des constructeurs et destructeur"
.PP 
.SS "CDoors::CDoors (\fBCSQLite_Local_DB\fP * BD)"

.SH "Documentation des fonctions membres"
.PP 
.SS "bool CDoors::CloseDoor (int idDoor)"

.SS "bool CDoors::CloseDoors (QList< int > DoorsList)"

.SS "bool CDoors::DoorIsClosed (int idDoor)"

.SS "bool CDoors::DoorsIsClosed (QList< int > DoorsList)"

.SS "QList< \fBstruct_DoorsStatus\fP > CDoors::DoorsStatus (QList< int > DoorsList)"

.SS "\fBstruct_DoorsStatus\fP CDoors::DoorStatus (int idDoor)"

.SS "bool CDoors::LockDoor (int idDoor)"

.SS "bool CDoors::LockDoors (QList< int > DoorsList)"

.SS "bool CDoors::OpenDoor (int idDoor)"

.SS "bool CDoors::OpenDoors (QList< int > DoorsList)"

.SS "bool CDoors::UnlockDoor (int idDoor)"

.SS "bool CDoors::UnlockDoors (QList< int > DoorsList)"


.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Locker_Control à partir du code source\&.
