.TH "Country" 3 "Vendredi 8 Mai 2015" "Version 1.2.2" "Locker_Control" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Country \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <country\&.h>\fP
.SS "Fonctions membres publiques"

.in +1c
.ti -1c
.RI "\fBCountry\fP ()"
.br
.ti -1c
.RI "\fB~Country\fP ()"
.br
.ti -1c
.RI "void \fBSetFrench\fP ()"
.br
.ti -1c
.RI "void \fBSetEnglish\fP ()"
.br
.ti -1c
.RI "void \fBSetDeutsch\fP ()"
.br
.ti -1c
.RI "void \fBSetEspanol\fP ()"
.br
.in -1c
.SH "Documentation des constructeurs et destructeur"
.PP 
.SS "Country::Country ()"

.SS "Country::~Country ()"

.SH "Documentation des fonctions membres"
.PP 
.SS "void Country::SetDeutsch ()"

.SS "void Country::SetEnglish ()"

.SS "void Country::SetEspanol ()"

.SS "void Country::SetFrench ()"


.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Locker_Control à partir du code source\&.
