.TH "S:/QT_CREATOR/Locker_Control/csqlite_local_db.h" 3 "Vendredi 8 Mai 2015" "Version 1.2.2" "Locker_Control" \" -*- nroff -*-
.ad l
.nh
.SH NAME
S:/QT_CREATOR/Locker_Control/csqlite_local_db.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <QString>\fP
.br
\fC#include <QtSql/QSqlDatabase>\fP
.br
\fC#include <QtSql/QSqlDriver>\fP
.br
\fC#include <QSqlQuery>\fP
.br
\fC#include <QSqlError>\fP
.br
\fC#include <QFile>\fP
.br
\fC#include <QObject>\fP
.br
\fC#include 'DataStructures\&.h'\fP
.br
\fC#include 'clms_db\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCSQLite_Local_DB\fP"
.br
.RI "\fIclasse \fBCSQLite_Local_DB\fP, gestion des communications entre une base de données locale de type SQLite, avec l'application LC (LockerControl)\&. \fP"
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBMAX_SQL_COLUMN_READ\fP   10"
.br
.in -1c
.SH "Documentation des macros"
.PP 
.SS "#define MAX_SQL_COLUMN_READ   10"

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Locker_Control à partir du code source\&.
