.TH "S:/QT_CREATOR/Locker_Control/customer.cpp" 3 "Vendredi 8 Mai 2015" "Version 1.2.2" "Locker_Control" \" -*- nroff -*-
.ad l
.nh
.SH NAME
S:/QT_CREATOR/Locker_Control/customer.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'customer\&.h'\fP
.br
\fC#include 'ui_customer\&.h'\fP
.br
\fC#include <QRegExpValidator>\fP
.br
\fC#include <QToolTip>\fP
.br
\fC#include <QDebug>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBVALID\fP   1"
.br
.ti -1c
.RI "#define \fBUNVALID\fP   0"
.br
.in -1c
.SH "Documentation des macros"
.PP 
.SS "#define UNVALID   0"

.SS "#define VALID   1"

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Locker_Control à partir du code source\&.
