.TH "Customer" 3 "Vendredi 8 Mai 2015" "Version 1.2.2" "Locker_Control" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Customer \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <customer\&.h>\fP
.PP
Est dérivée de QWidget\&.
.SS "Connecteurs publics"

.in +1c
.ti -1c
.RI "void \fBValid_Code\fP ()"
.br
.ti -1c
.RI "void \fBUpper\fP (QString)"
.br
.ti -1c
.RI "void \fBShowHome\fP ()"
.br
.in -1c
.SS "Signaux"

.in +1c
.ti -1c
.RI "void \fBSendListbox\fP (QList< int >)"
.br
.ti -1c
.RI "void \fBSendCode\fP (QString)"
.br
.ti -1c
.RI "void \fBrefresh\fP ()"
.br
.ti -1c
.RI "void \fBTextToUpper\fP (QString)"
.br
.in -1c
.SS "Fonctions membres publiques"

.in +1c
.ti -1c
.RI "\fBCustomer\fP (\fBCSQLite_Local_DB\fP *, QWidget *parent=0)"
.br
.ti -1c
.RI "void \fBSetShowWidgets\fP (\fBShowWidgets\fP *TShowWidgets)"
.br
.ti -1c
.RI "\fB~Customer\fP ()"
.br
.ti -1c
.RI "void \fBretranslateUi\fP ()"
.br
.in -1c
.SH "Documentation des constructeurs et destructeur"
.PP 
.SS "Customer::Customer (\fBCSQLite_Local_DB\fP * bd, QWidget * parent = \fC0\fP)\fC [explicit]\fP"

.SS "Customer::~Customer ()"

.SH "Documentation des fonctions membres"
.PP 
.SS "void Customer::refresh ()\fC [signal]\fP"

.SS "void Customer::retranslateUi ()"

.SS "void Customer::SendCode (QString)\fC [signal]\fP"

.SS "void Customer::SendListbox (QList< int >)\fC [signal]\fP"

.SS "void Customer::SetShowWidgets (\fBShowWidgets\fP * TShowWidgets)\fC [inline]\fP"

.SS "void Customer::ShowHome ()\fC [slot]\fP"

.SS "void Customer::TextToUpper (QString)\fC [signal]\fP"

.SS "void Customer::Upper (QString str)\fC [slot]\fP"

.SS "void Customer::Valid_Code ()\fC [slot]\fP"


.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Locker_Control à partir du code source\&.
