.TH "CustomTreeWidget" 3 "Vendredi 8 Mai 2015" "Version 1.2.2" "Locker_Control" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CustomTreeWidget \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <customtreewidget\&.h>\fP
.SS "Fonctions membres publiques"

.in +1c
.ti -1c
.RI "\fBCustomTreeWidget\fP (QTreeWidget *treewidget)"
.br
.ti -1c
.RI "\fB~CustomTreeWidget\fP ()"
.br
.ti -1c
.RI "void \fBAddItem\fP (int numberbox, \fBCustomPushButton\fP *button)"
.br
.ti -1c
.RI "void \fBEditedItem_ColumnStatusOfDoor\fP (int numberbox, QString textedited, QColor color)"
.br
.ti -1c
.RI "void \fBButtonVisible\fP (int numberbox, bool)"
.br
.ti -1c
.RI "void \fBClearListItem\fP ()"
.br
.ti -1c
.RI "bool \fBisDoorsClose\fP (QList< int > listbox)"
.br
.in -1c
.SH "Documentation des constructeurs et destructeur"
.PP 
.SS "CustomTreeWidget::CustomTreeWidget (QTreeWidget * treewidget)"

.SS "CustomTreeWidget::~CustomTreeWidget ()"

.SH "Documentation des fonctions membres"
.PP 
.SS "void CustomTreeWidget::AddItem (int numberbox, \fBCustomPushButton\fP * button)"

.SS "void CustomTreeWidget::ButtonVisible (int numberbox, bool status)"

.SS "void CustomTreeWidget::ClearListItem ()"

.SS "void CustomTreeWidget::EditedItem_ColumnStatusOfDoor (int numberbox, QString textedited, QColor color)"

.SS "bool CustomTreeWidget::isDoorsClose (QList< int > listbox)"


.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Locker_Control à partir du code source\&.
