.TH "S:/QT_CREATOR/Locker_Control/customtreewidget.cpp" 3 "Vendredi 8 Mai 2015" "Version 1.2.2" "Locker_Control" \" -*- nroff -*-
.ad l
.nh
.SH NAME
S:/QT_CREATOR/Locker_Control/customtreewidget.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'customtreewidget\&.h'\fP
.br
\fC#include <QHeaderView>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBC_DOORSNUMBERS\fP   0"
.br
.ti -1c
.RI "#define \fBC_STATUSOFDOORS\fP   1"
.br
.ti -1c
.RI "#define \fBC_REOPENINGDOORS\fP   2"
.br
.in -1c
.SH "Documentation des macros"
.PP 
.SS "#define C_DOORSNUMBERS   0"

.SS "#define C_REOPENINGDOORS   2"

.SS "#define C_STATUSOFDOORS   1"

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Locker_Control à partir du code source\&.
