.TH "CustomXml" 3 "Vendredi 8 Mai 2015" "Version 1.2.2" "Locker_Control" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CustomXml \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <customxml\&.h>\fP
.SS "Fonctions membres publiques"

.in +1c
.ti -1c
.RI "\fBCustomXml\fP (QString filename, QString Domroot)"
.br
.ti -1c
.RI "\fB~CustomXml\fP ()"
.br
.ti -1c
.RI "bool \fBOpenFileXml\fP (QIODevice::OpenMode mode=QIODevice::ReadWrite)"
.br
.ti -1c
.RI "void \fBCloseFileXml\fP ()"
.br
.ti -1c
.RI "bool \fBWriteFileXml\fP (QString childroot, QString element, QString attribut, QString value)"
.br
.ti -1c
.RI "bool \fBWriteFileXml\fP (QString childroot, QString element, QString attribut)"
.br
.ti -1c
.RI "QString \fBGetvalue\fP (QString childroot, QString element, QString attribut)"
.br
.ti -1c
.RI "bool \fBIsOpenFile\fP ()"
.br
.ti -1c
.RI "bool \fBIsFileXmlEmtpy\fP ()"
.br
.ti -1c
.RI "bool \fBisElemExist\fP (QString childroot, QString element)"
.br
.ti -1c
.RI "bool \fBisChildrootExist\fP (QString childroot)"
.br
.in -1c
.SH "Documentation des constructeurs et destructeur"
.PP 
.SS "CustomXml::CustomXml (QString filename, QString Domroot)"

.SS "CustomXml::~CustomXml ()"

.SH "Documentation des fonctions membres"
.PP 
.SS "void CustomXml::CloseFileXml ()"

.SS "QString CustomXml::Getvalue (QString childroot, QString element, QString attribut)"

.SS "bool CustomXml::isChildrootExist (QString childroot)"

.SS "bool CustomXml::isElemExist (QString childroot, QString element)"

.SS "bool CustomXml::IsFileXmlEmtpy ()"

.SS "bool CustomXml::IsOpenFile ()"

.SS "bool CustomXml::OpenFileXml (QIODevice::OpenMode mode = \fCQIODevice::ReadWrite\fP)"

.SS "bool CustomXml::WriteFileXml (QString childroot, QString element, QString attribut, QString value)"

.SS "bool CustomXml::WriteFileXml (QString childroot, QString element, QString attribut)"


.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Locker_Control à partir du code source\&.
