.TH "S:/QT_CREATOR/Locker_Control/customxml.h" 3 "Vendredi 8 Mai 2015" "Version 1.2.2" "Locker_Control" \" -*- nroff -*-
.ad l
.nh
.SH NAME
S:/QT_CREATOR/Locker_Control/customxml.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <QtXml>\fP
.br
\fC#include <QIODevice>\fP
.br
\fC#include <QFile>\fP
.br
\fC#include <QTextStream>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCustomXml\fP"
.br
.in -1c
.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Locker_Control à partir du code source\&.
