.TH "CustomPushButton" 3 "Vendredi 8 Mai 2015" "Version 1.2.2" "Locker_Control" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CustomPushButton \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <custompushbutton\&.h>\fP
.PP
Est dérivée de QPushButton\&.
.SS "Signaux"

.in +1c
.ti -1c
.RI "void \fBclicked\fP (QString)"
.br
.ti -1c
.RI "void \fBclicked\fP (int)"
.br
.in -1c
.SS "Fonctions membres publiques"

.in +1c
.ti -1c
.RI "\fBCustomPushButton\fP (int id, QString numpackage, QString file, QWidget *parent=0)"
.br
.ti -1c
.RI "\fBCustomPushButton\fP (int id, QString text, QWidget *parent=0)"
.br
.ti -1c
.RI "\fB~CustomPushButton\fP ()"
.br
.ti -1c
.RI "void \fBmousePressEvent\fP (QMouseEvent *event)"
.br
.ti -1c
.RI "void \fBsetDisabledB\fP (bool value)"
.br
.in -1c
.SH "Documentation des constructeurs et destructeur"
.PP 
.SS "CustomPushButton::CustomPushButton (int id, QString numpackage, QString file, QWidget * parent = \fC0\fP)"

.SS "CustomPushButton::CustomPushButton (int id, QString text, QWidget * parent = \fC0\fP)"

.SS "CustomPushButton::~CustomPushButton ()"

.SH "Documentation des fonctions membres"
.PP 
.SS "void CustomPushButton::clicked (QString)\fC [signal]\fP"

.SS "void CustomPushButton::clicked (int)\fC [signal]\fP"

.SS "void CustomPushButton::mousePressEvent (QMouseEvent * event)"

.SS "void CustomPushButton::setDisabledB (bool value)"


.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Locker_Control à partir du code source\&.
