.TH "S:/QT_CREATOR/Locker_Control/DataStructures.h" 3 "Vendredi 8 Mai 2015" "Version 1.2.2" "Locker_Control" \" -*- nroff -*-
.ad l
.nh
.SH NAME
S:/QT_CREATOR/Locker_Control/DataStructures.h \- Definnitions des formats de communications des données entre les classes de l'application LC\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <QString>\fP
.br
\fC#include <QList>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBstruct_PackagesUseBox\fP"
.br
.RI "\fIStructure de donnée de l'application LC, utilisée pour l'enregistrement des livraisons avec le contenu des consignes\&. \fP"
.ti -1c
.RI "struct \fBstruct_PackagesUseBox::struct_BoxContainment\fP"
.br
.RI "\fIStructure de donnée de l'application LC, inclus dans une 'struct_PackagesUseBox' utilisée pour renseigner le contenu des consignes\&. \fP"
.ti -1c
.RI "struct \fBstruct_DoorGeom\fP"
.br
.RI "\fIStructure de donnée de l'application LC, utilisée pour dessiner le plan de l'installation des consignes\&. \fP"
.ti -1c
.RI "struct \fBstruct_Database_Contains\fP"
.br
.RI "\fIStructure de donnée de l'application LC, utilisée pour l'enregistrement et lectures des fichiers de sauvegarde\&. \fP"
.ti -1c
.RI "struct \fBstruct_DoorsStatus\fP"
.br
.RI "\fIStructure de donnée de l'application LC, utilisée pour définir l'état des portes des consignes\&. \fP"
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBDEBUG\fP"
.br
.ti -1c
.RI "#define \fBEMPTY_DATABASE\fP   1"
.br
.ti -1c
.RI "#define \fBDEFAULT_DATABASE\fP   2"
.br
.ti -1c
.RI "#define \fBSAVE_DATABASE\fP   3"
.br
.ti -1c
.RI "#define \fBLOAD_SAVE_DATABASE\fP   4"
.br
.ti -1c
.RI "#define \fBUNDEFINED_USER\fP   -4"
.br
.ti -1c
.RI "#define \fBUNDEFINED_COMPANY_PASS\fP   -3"
.br
.ti -1c
.RI "#define \fBUNDEFINED_PERSONAL_PASS\fP   -2"
.br
.ti -1c
.RI "#define \fBUNDEFINED_PASSWORD\fP   -1"
.br
.ti -1c
.RI "#define \fBLIVREUR\fP   0"
.br
.ti -1c
.RI "#define \fBMAINTENANCE\fP   1"
.br
.ti -1c
.RI "#define \fBOK\fP   0"
.br
.ti -1c
.RI "#define \fBKO\fP   1"
.br
.ti -1c
.RI "#define \fBSELECTED\fP   2"
.br
.ti -1c
.RI "#define \fBNOCHECKED\fP   3"
.br
.in -1c
.SH "Description détaillée"
.PP 
Definnitions des formats de communications des données entre les classes de l'application LC\&. 


.PP
\fBAuteur:\fP
.RS 4
HOUDAYER Pierre
.RE
.PP
\fBVersion:\fP
.RS 4
1\&.3
.RE
.PP
\fBDate:\fP
.RS 4
8 mai 2015 
.RE
.PP

.SH "Documentation des macros"
.PP 
.SS "#define DEBUG"

.SS "#define DEFAULT_DATABASE   2"

.SS "#define EMPTY_DATABASE   1"

.SS "#define KO   1"

.SS "#define LIVREUR   0"

.SS "#define LOAD_SAVE_DATABASE   4"

.SS "#define MAINTENANCE   1"

.SS "#define NOCHECKED   3"

.SS "#define OK   0"

.SS "#define SAVE_DATABASE   3"

.SS "#define SELECTED   2"

.SS "#define UNDEFINED_COMPANY_PASS   -3"

.SS "#define UNDEFINED_PASSWORD   -1"

.SS "#define UNDEFINED_PERSONAL_PASS   -2"

.SS "#define UNDEFINED_USER   -4"

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Locker_Control à partir du code source\&.
