.TH "DeliveryConfirm" 3 "Vendredi 8 Mai 2015" "Version 1.2.2" "Locker_Control" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DeliveryConfirm \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <deliveryconfirm\&.h>\fP
.PP
Est dérivée de QWidget\&.
.SS "Connecteurs publics"

.in +1c
.ti -1c
.RI "void \fBNewDelivery\fP ()"
.br
.ti -1c
.RI "void \fBFinishDelivery\fP ()"
.br
.ti -1c
.RI "void \fBReceiveListPackageBox\fP (QList< \fBstruct_PackagesUseBox\fP > listpackagebox)"
.br
.ti -1c
.RI "void \fBSetValueProgress\fP (int)"
.br
.ti -1c
.RI "void \fBThreadFinished\fP ()"
.br
.in -1c
.SS "Signaux"

.in +1c
.ti -1c
.RI "void \fBSendListPackage\fP (QList< \fBstruct_PackagesUseBox\fP >)"
.br
.in -1c
.SS "Fonctions membres publiques"

.in +1c
.ti -1c
.RI "\fBDeliveryConfirm\fP (\fBCSQLite_Local_DB\fP *, \fBCLMS_DB\fP *, \fBStowPackages\fP *, \fBBoxChoice\fP *, QWidget *parent=0)"
.br
.ti -1c
.RI "void \fBSetShowWidgets\fP (\fBShowWidgets\fP *TShowWidgets)"
.br
.ti -1c
.RI "void \fBSaveDelivery\fP ()"
.br
.ti -1c
.RI "\fB~DeliveryConfirm\fP ()"
.br
.ti -1c
.RI "void \fBretranslateUi\fP ()"
.br
.in -1c
.SH "Documentation des constructeurs et destructeur"
.PP 
.SS "DeliveryConfirm::DeliveryConfirm (\fBCSQLite_Local_DB\fP * db, \fBCLMS_DB\fP * lms, \fBStowPackages\fP * WStowPackage, \fBBoxChoice\fP * WBoxChoice, QWidget * parent = \fC0\fP)\fC [explicit]\fP"

.SS "DeliveryConfirm::~DeliveryConfirm ()"

.SH "Documentation des fonctions membres"
.PP 
.SS "void DeliveryConfirm::FinishDelivery ()\fC [slot]\fP"

.SS "void DeliveryConfirm::NewDelivery ()\fC [slot]\fP"

.SS "void DeliveryConfirm::ReceiveListPackageBox (QList< \fBstruct_PackagesUseBox\fP > listpackagebox)\fC [slot]\fP"

.SS "void DeliveryConfirm::retranslateUi ()"

.SS "void DeliveryConfirm::SaveDelivery ()"

.SS "void DeliveryConfirm::SendListPackage (QList< \fBstruct_PackagesUseBox\fP >)\fC [signal]\fP"

.SS "void DeliveryConfirm::SetShowWidgets (\fBShowWidgets\fP * TShowWidgets)\fC [inline]\fP"

.SS "void DeliveryConfirm::SetValueProgress (int val)\fC [slot]\fP"

.SS "void DeliveryConfirm::ThreadFinished ()\fC [slot]\fP"


.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Locker_Control à partir du code source\&.
