.TH "DoorsManager" 3 "Vendredi 8 Mai 2015" "Version 1.2.2" "Locker_Control" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DoorsManager \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <doorsmanager\&.h>\fP
.PP
Est dérivée de QWidget\&.
.SS "Connecteurs publics"

.in +1c
.ti -1c
.RI "void \fBReturnHome\fP ()"
.br
.ti -1c
.RI "void \fBReturnSettingsMenu\fP ()"
.br
.ti -1c
.RI "void \fBReturnMaintenanceMenu\fP ()"
.br
.ti -1c
.RI "void \fBRunTestBox\fP (int idBox)"
.br
.ti -1c
.RI "void \fBGotoDoorsManager\fP ()"
.br
.ti -1c
.RI "void \fBGotoDoorsTest\fP ()"
.br
.ti -1c
.RI "void \fBGotoAddDelDoors\fP ()"
.br
.ti -1c
.RI "void \fBGotoActDesDoors\fP ()"
.br
.ti -1c
.RI "void \fBUnlockBox\fP ()"
.br
.ti -1c
.RI "void \fBOpenBox\fP ()"
.br
.ti -1c
.RI "void \fBCheckTestBox\fP ()"
.br
.ti -1c
.RI "void \fBActionOpenBox_ConfirmSwap\fP ()"
.br
.ti -1c
.RI "void \fBActionUnlockBox_ConfirmSwap\fP ()"
.br
.ti -1c
.RI "void \fBActivateDoor\fP ()"
.br
.ti -1c
.RI "void \fBDesactivateDoor\fP ()"
.br
.ti -1c
.RI "void \fBRunActDesBox\fP (int idBox)"
.br
.in -1c
.SS "Signaux"

.in +1c
.ti -1c
.RI "void \fBStartRunActDesBox\fP (int idBox)"
.br
.in -1c
.SS "Fonctions membres publiques"

.in +1c
.ti -1c
.RI "\fBDoorsManager\fP (QWidget *parent=0, \fBCSQLite_Local_DB\fP *BD=NULL, \fBCDoors\fP *Doors=NULL)"
.br
.ti -1c
.RI "void \fBSetShowWidgets\fP (\fBShowWidgets\fP *TShowWidgets)"
.br
.ti -1c
.RI "void \fBCreateBoxesViewTest\fP ()"
.br
.ti -1c
.RI "void \fBCreateBoxesViewActDes\fP ()"
.br
.ti -1c
.RI "\fB~DoorsManager\fP ()"
.br
.ti -1c
.RI "QList< \fBstruct_DoorsStatus\fP > \fBBoxesStatusSort\fP (QList< \fBstruct_DoorsStatus\fP > listtmp)"
.br
.in -1c
.SH "Documentation des constructeurs et destructeur"
.PP 
.SS "DoorsManager::DoorsManager (QWidget * parent = \fC0\fP, \fBCSQLite_Local_DB\fP * BD = \fCNULL\fP, \fBCDoors\fP * Doors = \fCNULL\fP)\fC [explicit]\fP"

.SS "DoorsManager::~DoorsManager ()"

.SH "Documentation des fonctions membres"
.PP 
.SS "void DoorsManager::ActionOpenBox_ConfirmSwap ()\fC [slot]\fP"

.SS "void DoorsManager::ActionUnlockBox_ConfirmSwap ()\fC [slot]\fP"

.SS "void DoorsManager::ActivateDoor ()\fC [slot]\fP"

.SS "QList< \fBstruct_DoorsStatus\fP > DoorsManager::BoxesStatusSort (QList< \fBstruct_DoorsStatus\fP > listtmp)"

.SS "void DoorsManager::CheckTestBox ()\fC [slot]\fP"

.SS "void DoorsManager::CreateBoxesViewActDes ()"

.SS "void DoorsManager::CreateBoxesViewTest ()"

.SS "void DoorsManager::DesactivateDoor ()\fC [slot]\fP"

.SS "void DoorsManager::GotoActDesDoors ()\fC [slot]\fP"

.SS "void DoorsManager::GotoAddDelDoors ()\fC [slot]\fP"

.SS "void DoorsManager::GotoDoorsManager ()\fC [slot]\fP"

.SS "void DoorsManager::GotoDoorsTest ()\fC [slot]\fP"

.SS "void DoorsManager::OpenBox ()\fC [slot]\fP"

.SS "void DoorsManager::ReturnHome ()\fC [inline]\fP, \fC [slot]\fP"

.SS "void DoorsManager::ReturnMaintenanceMenu ()\fC [inline]\fP, \fC [slot]\fP"

.SS "void DoorsManager::ReturnSettingsMenu ()\fC [inline]\fP, \fC [slot]\fP"

.SS "void DoorsManager::RunActDesBox (int idBox)\fC [slot]\fP"

.SS "void DoorsManager::RunTestBox (int idBox)\fC [slot]\fP"

.SS "void DoorsManager::SetShowWidgets (\fBShowWidgets\fP * TShowWidgets)\fC [inline]\fP"

.SS "void DoorsManager::StartRunActDesBox (int idBox)\fC [signal]\fP"

.SS "void DoorsManager::UnlockBox ()\fC [slot]\fP"


.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Locker_Control à partir du code source\&.
