.TH "S:/QT_CREATOR/Locker_Control/doorsmanager.h" 3 "Vendredi 8 Mai 2015" "Version 1.2.2" "Locker_Control" \" -*- nroff -*-
.ad l
.nh
.SH NAME
S:/QT_CREATOR/Locker_Control/doorsmanager.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <QWidget>\fP
.br
\fC#include 'csqlite_local_db\&.h'\fP
.br
\fC#include 'showwidgets\&.h'\fP
.br
\fC#include 'cdoors\&.h'\fP
.br
\fC#include 'customtreewidget\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBDoorsManager\fP"
.br
.in -1c
.SS "Espaces de nommage"

.in +1c
.ti -1c
.RI " \fBUi\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBWINDEX_DOORS_MANAGER\fP   0"
.br
.ti -1c
.RI "#define \fBWINDEX_DOORS_TEST\fP   1"
.br
.ti -1c
.RI "#define \fBWINDEX_ADD_DEL_DOORS\fP   2"
.br
.ti -1c
.RI "#define \fBWINDEX_ACT_DES_DOORS\fP   3"
.br
.ti -1c
.RI "#define \fBWINDEX_DOORS_TEST_ACTIONS\fP   4"
.br
.ti -1c
.RI "#define \fBWINDEX_DOORS_TEST_CONFIRM\fP   5"
.br
.ti -1c
.RI "#define \fBWINDEX_DOORS_ACT_DES_COMMAND\fP   6"
.br
.in -1c
.SH "Documentation des macros"
.PP 
.SS "#define WINDEX_ACT_DES_DOORS   3"

.SS "#define WINDEX_ADD_DEL_DOORS   2"

.SS "#define WINDEX_DOORS_ACT_DES_COMMAND   6"

.SS "#define WINDEX_DOORS_MANAGER   0"

.SS "#define WINDEX_DOORS_TEST   1"

.SS "#define WINDEX_DOORS_TEST_ACTIONS   4"

.SS "#define WINDEX_DOORS_TEST_CONFIRM   5"

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Locker_Control à partir du code source\&.
