.TH "S:/QT_CREATOR/Locker_Control/editsettingsystem.h" 3 "Vendredi 8 Mai 2015" "Version 1.2.2" "Locker_Control" \" -*- nroff -*-
.ad l
.nh
.SH NAME
S:/QT_CREATOR/Locker_Control/editsettingsystem.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <QWidget>\fP
.br
\fC#include <QLineEdit>\fP
.br
\fC#include <QRegExpValidator>\fP
.br
\fC#include 'settingsystem\&.h'\fP
.br
\fC#include 'showwidgets\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBEditSettingSystem\fP"
.br
.in -1c
.SS "Espaces de nommage"

.in +1c
.ti -1c
.RI " \fBUi\fP"
.br
.in -1c
.SS "Énumérations"

.in +1c
.ti -1c
.RI "enum \fBMODE_REGEXP\fP { \fBNORMAL\fP = 0, \fBIPV4\fP = 1, \fBEMAIL\fP =2 }"
.br
.in -1c
.SH "Documentation du type de l'énumération"
.PP 
.SS "enum \fBMODE_REGEXP\fP"

.PP
\fBValeurs énumérées\fP
.in +1c
.TP
\fB\fINORMAL \fP\fP
.TP
\fB\fIIPV4 \fP\fP
.TP
\fB\fIEMAIL \fP\fP
.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Locker_Control à partir du code source\&.
