.TH "EditSettingSystem" 3 "Vendredi 8 Mai 2015" "Version 1.2.2" "Locker_Control" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EditSettingSystem \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <editsettingsystem\&.h>\fP
.PP
Est dérivée de QWidget\&.
.SS "Connecteurs publics"

.in +1c
.ti -1c
.RI "void \fBreceiveEditText\fP (QString label, QString text, \fBMODE_REGEXP\fP)"
.br
.ti -1c
.RI "void \fBClickedButtonOK\fP ()"
.br
.ti -1c
.RI "void \fBSupprCaract\fP ()"
.br
.ti -1c
.RI "void \fBSetCaract\fP (QChar)"
.br
.in -1c
.SS "Signaux"

.in +1c
.ti -1c
.RI "void \fBsendTextEdit\fP (QString)"
.br
.in -1c
.SS "Fonctions membres publiques"

.in +1c
.ti -1c
.RI "\fBEditSettingSystem\fP (\fBSettingSystem\fP *settingsystem, QWidget *parent=0)"
.br
.ti -1c
.RI "void \fBSetShowWidgets\fP (\fBShowWidgets\fP *TShowWidgets)"
.br
.ti -1c
.RI "\fB~EditSettingSystem\fP ()"
.br
.in -1c
.SH "Documentation des constructeurs et destructeur"
.PP 
.SS "EditSettingSystem::EditSettingSystem (\fBSettingSystem\fP * settingsystem, QWidget * parent = \fC0\fP)\fC [explicit]\fP"

.SS "EditSettingSystem::~EditSettingSystem ()"

.SH "Documentation des fonctions membres"
.PP 
.SS "void EditSettingSystem::ClickedButtonOK ()\fC [slot]\fP"

.SS "void EditSettingSystem::receiveEditText (QString label, QString text, \fBMODE_REGEXP\fP mode)\fC [slot]\fP"

.SS "void EditSettingSystem::sendTextEdit (QString)\fC [signal]\fP"

.SS "void EditSettingSystem::SetCaract (QChar caract)\fC [slot]\fP"

.SS "void EditSettingSystem::SetShowWidgets (\fBShowWidgets\fP * TShowWidgets)\fC [inline]\fP"

.SS "void EditSettingSystem::SupprCaract ()\fC [slot]\fP"


.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Locker_Control à partir du code source\&.
