.TH "S:/QT_CREATOR/Locker_Control/keyboard.h" 3 "Vendredi 8 Mai 2015" "Version 1.2.2" "Locker_Control" \" -*- nroff -*-
.ad l
.nh
.SH NAME
S:/QT_CREATOR/Locker_Control/keyboard.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <QWidget>\fP
.br
\fC#include <QPushButton>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBKeyBoard\fP"
.br
.in -1c
.SS "Espaces de nommage"

.in +1c
.ti -1c
.RI " \fBUi\fP"
.br
.in -1c
.SS "Énumérations"

.in +1c
.ti -1c
.RI "enum \fBMODE\fP { \fBUPPER\fP = 0, \fBLOWER\fP = 1, \fBNUM\fP = 2 }"
.br
.in -1c
.SH "Documentation du type de l'énumération"
.PP 
.SS "enum \fBMODE\fP"

.PP
\fBValeurs énumérées\fP
.in +1c
.TP
\fB\fIUPPER \fP\fP
.TP
\fB\fILOWER \fP\fP
.TP
\fB\fINUM \fP\fP
.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Locker_Control à partir du code source\&.
