.TH "S:/QT_CREATOR/Locker_Control/login.cpp" 3 "Vendredi 8 Mai 2015" "Version 1.2.2" "Locker_Control" \" -*- nroff -*-
.ad l
.nh
.SH NAME
S:/QT_CREATOR/Locker_Control/login.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'login\&.h'\fP
.br
\fC#include 'ui_login\&.h'\fP
.br
\fC#include <QDebug>\fP
.br
\fC#include <QValidator>\fP
.br
\fC#include <QRegExpValidator>\fP
.br
\fC#include <QScrollBar>\fP
.br
\fC#include <QToolTip>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBMAINTENANCE\fP   1"
.br
.ti -1c
.RI "#define \fBDELIVERYMAN\fP   0"
.br
.ti -1c
.RI "#define \fBERROR_PASSWD\fP   -1"
.br
.ti -1c
.RI "#define \fBERROR_ID\fP   -2"
.br
.ti -1c
.RI "#define \fBERROR_COMPANY\fP   -3"
.br
.ti -1c
.RI "#define \fBERROR_LOGIN\fP   -4"
.br
.ti -1c
.RI "#define \fBED_SOCIETE\fP   0"
.br
.ti -1c
.RI "#define \fBED_ID\fP   1"
.br
.ti -1c
.RI "#define \fBED_PASSWD\fP   2"
.br
.in -1c
.SH "Documentation des macros"
.PP 
.SS "#define DELIVERYMAN   0"

.SS "#define ED_ID   1"

.SS "#define ED_PASSWD   2"

.SS "#define ED_SOCIETE   0"

.SS "#define ERROR_COMPANY   -3"

.SS "#define ERROR_ID   -2"

.SS "#define ERROR_LOGIN   -4"

.SS "#define ERROR_PASSWD   -1"

.SS "#define MAINTENANCE   1"

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Locker_Control à partir du code source\&.
