.TH "S:/QT_CREATOR/Locker_Control/main.cpp" 3 "Vendredi 8 Mai 2015" "Version 1.2.2" "Locker_Control" \" -*- nroff -*-
.ad l
.nh
.SH NAME
S:/QT_CREATOR/Locker_Control/main.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <QApplication>\fP
.br
\fC#include <QTextCodec>\fP
.br
\fC#include 'consolewindows\&.h'\fP
.br

.SS "Fonctions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char *argv[])"
.br
.in -1c
.SH "Documentation des fonctions"
.PP 
.SS "int main (int argc, char * argv[])"

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Locker_Control à partir du code source\&.
