.TH "md__s_1__q_t__c_r_e_a_t_o_r__locker__control__r_e_a_d_m_e" 3 "Vendredi 8 Mai 2015" "Version 1.2.2" "Locker_Control" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__s_1__q_t__c_r_e_a_t_o_r__locker__control__r_e_a_d_m_e \- Locker_Control 

.SS "The application Locker Control (LC), is an automatic boxes manager on Qt in c++\&."
.PP
.SS "Uses cases status : WORK IN PROGRESS"
.PP
.IP "\(bu" 2
System settings configuration : * WORK IN PROGRESS
.IP "\(bu" 2
Site configuration : - NOT STARTED
.IP "\(bu" 2
Doors locking : + TERMINATED
.IP "\(bu" 2
Doors activating : + TERMINATED
.IP "\(bu" 2
Doors deleting : - NOT STARTED
.IP "\(bu" 2
Doors adding : - NOT STARTED
.IP "\(bu" 2
Status checking : + TERMINATED
.IP "\(bu" 2
Doors test : + TERMINATED
.IP "\(bu" 2
LC Restarting : - NOT STARTED
.IP "\(bu" 2
Database rebuilding : + TERMINATED
.IP "\(bu" 2
Total reset : - NOT STARTED
.IP "\(bu" 2
Delivering packages : + TERMINATED
.IP "\(bu" 2
Extracting packages : + TERMINATED
.IP "\(bu" 2
verification boxes : + TERMINATED
.IP "\(bu" 2
Leave a message (Help module) : - NOT STARTED
.IP "\(bu" 2
LC Controled by SSH (Help module) : - NOT STARTED
.PP
.PP
.SS "- - - - - - - - - - - Currently out of the project - - - - - - - - - - - -"
.PP
.IP "\(bu" 2
LC updating by LMS : - UNDISCLOSED
.IP "\(bu" 2
LMS database updating : - UNDISCLOSED
.IP "\(bu" 2
System updating : - UNDISCLOSED 
.PP

