.TH "MenuDelivery" 3 "Vendredi 8 Mai 2015" "Version 1.2.2" "Locker_Control" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MenuDelivery \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <menudelivery\&.h>\fP
.PP
Est dérivée de QWidget\&.
.SS "Connecteurs publics"

.in +1c
.ti -1c
.RI "void \fBDeposit\fP ()"
.br
.ti -1c
.RI "void \fBOpenBoxEmpty\fP ()"
.br
.ti -1c
.RI "void \fBReturnHome\fP ()"
.br
.in -1c
.SS "Signaux"

.in +1c
.ti -1c
.RI "void \fBrefreshGraphicsBox\fP ()"
.br
.ti -1c
.RI "void \fBshowDoors\fP ()"
.br
.in -1c
.SS "Fonctions membres publiques"

.in +1c
.ti -1c
.RI "\fBMenuDelivery\fP (QWidget *parent=0)"
.br
.ti -1c
.RI "void \fBSetShowWidgets\fP (\fBShowWidgets\fP *TShowWidgets)"
.br
.ti -1c
.RI "\fB~MenuDelivery\fP ()"
.br
.ti -1c
.RI "void \fBretranslateUi\fP ()"
.br
.in -1c
.SH "Documentation des constructeurs et destructeur"
.PP 
.SS "MenuDelivery::MenuDelivery (QWidget * parent = \fC0\fP)\fC [explicit]\fP"

.SS "MenuDelivery::~MenuDelivery ()"

.SH "Documentation des fonctions membres"
.PP 
.SS "void MenuDelivery::Deposit ()\fC [slot]\fP"

.SS "void MenuDelivery::OpenBoxEmpty ()\fC [slot]\fP"

.SS "void MenuDelivery::refreshGraphicsBox ()\fC [signal]\fP"

.SS "void MenuDelivery::retranslateUi ()"

.SS "void MenuDelivery::ReturnHome ()\fC [slot]\fP"

.SS "void MenuDelivery::SetShowWidgets (\fBShowWidgets\fP * TShowWidgets)\fC [inline]\fP"

.SS "void MenuDelivery::showDoors ()\fC [signal]\fP"


.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Locker_Control à partir du code source\&.
