.TH "OpenEmptyBox" 3 "Vendredi 8 Mai 2015" "Version 1.2.2" "Locker_Control" \" -*- nroff -*-
.ad l
.nh
.SH NAME
OpenEmptyBox \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <openemptybox\&.h>\fP
.PP
Est dérivée de QWidget\&.
.SS "Connecteurs publics"

.in +1c
.ti -1c
.RI "void \fBReturnMenuDelivery\fP ()"
.br
.ti -1c
.RI "void \fBCreateListBoxEmpty\fP ()"
.br
.ti -1c
.RI "void \fBStatusDoors\fP (\fBstruct_DoorsStatus\fP doorstatus)"
.br
.ti -1c
.RI "void \fBOpenDoor\fP (int door)"
.br
.in -1c
.SS "Fonctions membres publiques"

.in +1c
.ti -1c
.RI "\fBOpenEmptyBox\fP (\fBCSQLite_Local_DB\fP *bd, \fBMenuDelivery\fP *WMenuDelivery, \fBCDoors\fP *Doors, QWidget *parent=0)"
.br
.ti -1c
.RI "void \fBSetShowWidgets\fP (\fBShowWidgets\fP *TShowWidgets)"
.br
.ti -1c
.RI "void \fBReinitializeAttribut\fP ()"
.br
.ti -1c
.RI "\fB~OpenEmptyBox\fP ()"
.br
.ti -1c
.RI "void \fBretranslateUi\fP ()"
.br
.ti -1c
.RI "void \fBShowMessageError\fP (QString mes)"
.br
.in -1c
.SH "Documentation des constructeurs et destructeur"
.PP 
.SS "OpenEmptyBox::OpenEmptyBox (\fBCSQLite_Local_DB\fP * bd, \fBMenuDelivery\fP * WMenuDelivery, \fBCDoors\fP * Doors, QWidget * parent = \fC0\fP)\fC [explicit]\fP"

.SS "OpenEmptyBox::~OpenEmptyBox ()"

.SH "Documentation des fonctions membres"
.PP 
.SS "void OpenEmptyBox::CreateListBoxEmpty ()\fC [slot]\fP"

.SS "void OpenEmptyBox::OpenDoor (int door)\fC [slot]\fP"

.SS "void OpenEmptyBox::ReinitializeAttribut ()"

.SS "void OpenEmptyBox::retranslateUi ()"

.SS "void OpenEmptyBox::ReturnMenuDelivery ()\fC [slot]\fP"

.SS "void OpenEmptyBox::SetShowWidgets (\fBShowWidgets\fP * TShowWidgets)\fC [inline]\fP"

.SS "void OpenEmptyBox::ShowMessageError (QString mes)"

.SS "void OpenEmptyBox::StatusDoors (\fBstruct_DoorsStatus\fP doorstatus)\fC [slot]\fP"


.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Locker_Control à partir du code source\&.
