.TH "S:/QT_CREATOR/Locker_Control/settingsystem.cpp" 3 "Vendredi 8 Mai 2015" "Version 1.2.2" "Locker_Control" \" -*- nroff -*-
.ad l
.nh
.SH NAME
S:/QT_CREATOR/Locker_Control/settingsystem.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'settingsystem\&.h'\fP
.br
\fC#include 'ui_settingsystem\&.h'\fP
.br
\fC#include <QRegExpValidator>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBED_CODE\fP   0"
.br
.ti -1c
.RI "#define \fBED_SITE\fP   1"
.br
.ti -1c
.RI "#define \fBED_NETWORK_IP\fP   2"
.br
.ti -1c
.RI "#define \fBED_NETWORK_MASK\fP   3"
.br
.ti -1c
.RI "#define \fBED_NETWORK_GATEWAY\fP   4"
.br
.ti -1c
.RI "#define \fBED_NETWORK_DNS1\fP   5"
.br
.ti -1c
.RI "#define \fBED_NETWORK_DNS2\fP   6"
.br
.ti -1c
.RI "#define \fBED_LMS_IP\fP   7"
.br
.ti -1c
.RI "#define \fBED_RSYNC_IP\fP   8"
.br
.ti -1c
.RI "#define \fBED_RSYNC_USER\fP   9"
.br
.ti -1c
.RI "#define \fBED_RSYNC_PASSWD\fP   10"
.br
.ti -1c
.RI "#define \fBED_SOFTPHONE_USER\fP   11"
.br
.ti -1c
.RI "#define \fBED_SOFTPHONE_PASSWD\fP   12"
.br
.ti -1c
.RI "#define \fBED_SOFTPHONE_DOMAIN\fP   13"
.br
.ti -1c
.RI "#define \fBED_SOFTPHONE_PROXY\fP   14"
.br
.in -1c
.SH "Documentation des macros"
.PP 
.SS "#define ED_CODE   0"

.SS "#define ED_LMS_IP   7"

.SS "#define ED_NETWORK_DNS1   5"

.SS "#define ED_NETWORK_DNS2   6"

.SS "#define ED_NETWORK_GATEWAY   4"

.SS "#define ED_NETWORK_IP   2"

.SS "#define ED_NETWORK_MASK   3"

.SS "#define ED_RSYNC_IP   8"

.SS "#define ED_RSYNC_PASSWD   10"

.SS "#define ED_RSYNC_USER   9"

.SS "#define ED_SITE   1"

.SS "#define ED_SOFTPHONE_DOMAIN   13"

.SS "#define ED_SOFTPHONE_PASSWD   12"

.SS "#define ED_SOFTPHONE_PROXY   14"

.SS "#define ED_SOFTPHONE_USER   11"

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Locker_Control à partir du code source\&.
