.TH "Setting" 3 "Vendredi 8 Mai 2015" "Version 1.2.2" "Locker_Control" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Setting \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <setting\&.h>\fP
.PP
Est dérivée de QWidget\&.
.SS "Connecteurs publics"

.in +1c
.ti -1c
.RI "void \fBReturnHome\fP ()"
.br
.ti -1c
.RI "void \fBShowMaintenanceMenu\fP ()"
.br
.in -1c
.SS "Fonctions membres publiques"

.in +1c
.ti -1c
.RI "\fBSetting\fP (QWidget *parent=0)"
.br
.ti -1c
.RI "void \fBSetShowWidgets\fP (\fBShowWidgets\fP *TShowWidgets)"
.br
.ti -1c
.RI "\fB~Setting\fP ()"
.br
.ti -1c
.RI "void \fBretranslateUi\fP ()"
.br
.in -1c
.SH "Documentation des constructeurs et destructeur"
.PP 
.SS "Setting::Setting (QWidget * parent = \fC0\fP)\fC [explicit]\fP"

.SS "Setting::~Setting ()"

.SH "Documentation des fonctions membres"
.PP 
.SS "void Setting::retranslateUi ()"

.SS "void Setting::ReturnHome ()\fC [slot]\fP"

.SS "void Setting::SetShowWidgets (\fBShowWidgets\fP * TShowWidgets)\fC [inline]\fP"

.SS "void Setting::ShowMaintenanceMenu ()\fC [slot]\fP"


.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Locker_Control à partir du code source\&.
