.TH "ShowWidgets" 3 "Vendredi 8 Mai 2015" "Version 1.2.2" "Locker_Control" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ShowWidgets \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <showwidgets\&.h>\fP
.SS "Fonctions membres publiques"

.in +1c
.ti -1c
.RI "\fBShowWidgets\fP ()"
.br
.ti -1c
.RI "\fB~ShowWidgets\fP ()"
.br
.ti -1c
.RI "int \fBGetPosConsoleWindows\fP ()"
.br
.ti -1c
.RI "int \fBGetPosBoxChoice\fP ()"
.br
.ti -1c
.RI "int \fBGetPosCustomer\fP ()"
.br
.ti -1c
.RI "int \fBGetPosDeliveryConfirm\fP ()"
.br
.ti -1c
.RI "int \fBGetPosLogin\fP ()"
.br
.ti -1c
.RI "int \fBGetPosMenuDelivery\fP ()"
.br
.ti -1c
.RI "int \fBGetPosOpenEmptyBox\fP ()"
.br
.ti -1c
.RI "int \fBGetPosScanPackage\fP ()"
.br
.ti -1c
.RI "int \fBGetPosShowPackageBox\fP ()"
.br
.ti -1c
.RI "int \fBGetPosSetting\fP ()"
.br
.ti -1c
.RI "int \fBGetPosSettingSystem\fP ()"
.br
.ti -1c
.RI "int \fBGetPosStowPackages\fP ()"
.br
.ti -1c
.RI "int \fBGetPosMaintenanceMenu\fP ()"
.br
.ti -1c
.RI "int \fBGetPosDoorsManager\fP ()"
.br
.ti -1c
.RI "int \fBGetPosSQLite_Local_DatabaseManager\fP ()"
.br
.ti -1c
.RI "int \fBGetPosEditSettingSystem\fP ()"
.br
.ti -1c
.RI "template<typename T > T * \fBGetWidget\fP (int pos)"
.br
.ti -1c
.RI "void \fBSetStackedWidget\fP (QStackedWidget *stackedW)"
.br
.ti -1c
.RI "void \fBSetPosConsoleWindows\fP (int TposConsole)"
.br
.ti -1c
.RI "void \fBSetPosBoxChoice\fP (int TposBoxChoice)"
.br
.ti -1c
.RI "void \fBSetPosCustomer\fP (int TposCustumer)"
.br
.ti -1c
.RI "void \fBSetPosDeliveryConfirm\fP (int TposDeliComf)"
.br
.ti -1c
.RI "void \fBSetPosLogin\fP (int TposLogin)"
.br
.ti -1c
.RI "void \fBSetPosMenuDelivery\fP (int TposMenuDeli)"
.br
.ti -1c
.RI "void \fBSetPosOpenEmptyBox\fP (int TposOpenEmptybox)"
.br
.ti -1c
.RI "void \fBSetPosScanPackage\fP (int TposScanPackage)"
.br
.ti -1c
.RI "void \fBSetPosShowPackageBox\fP (int TposShowPackageBox)"
.br
.ti -1c
.RI "void \fBSetPosSetting\fP (int TposSetting)"
.br
.ti -1c
.RI "void \fBSetPosSettingSystem\fP (int TposSettingSystem)"
.br
.ti -1c
.RI "void \fBSetPosStowPackages\fP (int TposStowPackage)"
.br
.ti -1c
.RI "void \fBSetPosMaintenanceMenu\fP (int TposMaintenanceMenu)"
.br
.ti -1c
.RI "void \fBsetPosDoorsManager\fP (int TposDoorsManager)"
.br
.ti -1c
.RI "void \fBSetPosSQLite_Local_DatabaseManager\fP (int TposSQLite_Local_DatabaseManager)"
.br
.ti -1c
.RI "void \fBSetPosEditSettingSystem\fP (int TposEditSettingSystem)"
.br
.ti -1c
.RI "void \fBShowWConsoleWindows\fP ()"
.br
.ti -1c
.RI "void \fBShowWBoxChoice\fP ()"
.br
.ti -1c
.RI "void \fBShowWCustomer\fP ()"
.br
.ti -1c
.RI "void \fBShowWDeliveryConfirm\fP ()"
.br
.ti -1c
.RI "void \fBShowWLogin\fP ()"
.br
.ti -1c
.RI "void \fBShowWMenuDelivery\fP ()"
.br
.ti -1c
.RI "void \fBShowWOpenEmptyBox\fP ()"
.br
.ti -1c
.RI "void \fBShowWScanPackage\fP ()"
.br
.ti -1c
.RI "void \fBShowWPackageBox\fP ()"
.br
.ti -1c
.RI "void \fBShowWSetting\fP ()"
.br
.ti -1c
.RI "void \fBShowWStowPackages\fP ()"
.br
.ti -1c
.RI "void \fBShowWMaintenanceMenu\fP ()"
.br
.ti -1c
.RI "void \fBShowWDoorsManager\fP ()"
.br
.ti -1c
.RI "void \fBShowWSQLite_Local_DatabaseManager\fP ()"
.br
.ti -1c
.RI "void \fBShowWSettingSystem\fP ()"
.br
.ti -1c
.RI "void \fBShowWEditSettingSystem\fP ()"
.br
.in -1c
.SH "Documentation des constructeurs et destructeur"
.PP 
.SS "ShowWidgets::ShowWidgets ()"

.SS "ShowWidgets::~ShowWidgets ()"

.SH "Documentation des fonctions membres"
.PP 
.SS "int ShowWidgets::GetPosBoxChoice ()\fC [inline]\fP"

.SS "int ShowWidgets::GetPosConsoleWindows ()\fC [inline]\fP"

.SS "int ShowWidgets::GetPosCustomer ()\fC [inline]\fP"

.SS "int ShowWidgets::GetPosDeliveryConfirm ()\fC [inline]\fP"

.SS "int ShowWidgets::GetPosDoorsManager ()\fC [inline]\fP"

.SS "int ShowWidgets::GetPosEditSettingSystem ()\fC [inline]\fP"

.SS "int ShowWidgets::GetPosLogin ()\fC [inline]\fP"

.SS "int ShowWidgets::GetPosMaintenanceMenu ()\fC [inline]\fP"

.SS "int ShowWidgets::GetPosMenuDelivery ()\fC [inline]\fP"

.SS "int ShowWidgets::GetPosOpenEmptyBox ()\fC [inline]\fP"

.SS "int ShowWidgets::GetPosScanPackage ()\fC [inline]\fP"

.SS "int ShowWidgets::GetPosSetting ()\fC [inline]\fP"

.SS "int ShowWidgets::GetPosSettingSystem ()\fC [inline]\fP"

.SS "int ShowWidgets::GetPosShowPackageBox ()\fC [inline]\fP"

.SS "int ShowWidgets::GetPosSQLite_Local_DatabaseManager ()\fC [inline]\fP"

.SS "int ShowWidgets::GetPosStowPackages ()\fC [inline]\fP"

.SS "template<typename T > T* ShowWidgets::GetWidget (int pos)\fC [inline]\fP"

.SS "void ShowWidgets::SetPosBoxChoice (int TposBoxChoice)\fC [inline]\fP"

.SS "void ShowWidgets::SetPosConsoleWindows (int TposConsole)\fC [inline]\fP"

.SS "void ShowWidgets::SetPosCustomer (int TposCustumer)\fC [inline]\fP"

.SS "void ShowWidgets::SetPosDeliveryConfirm (int TposDeliComf)\fC [inline]\fP"

.SS "void ShowWidgets::setPosDoorsManager (int TposDoorsManager)\fC [inline]\fP"

.SS "void ShowWidgets::SetPosEditSettingSystem (int TposEditSettingSystem)\fC [inline]\fP"

.SS "void ShowWidgets::SetPosLogin (int TposLogin)\fC [inline]\fP"

.SS "void ShowWidgets::SetPosMaintenanceMenu (int TposMaintenanceMenu)\fC [inline]\fP"

.SS "void ShowWidgets::SetPosMenuDelivery (int TposMenuDeli)\fC [inline]\fP"

.SS "void ShowWidgets::SetPosOpenEmptyBox (int TposOpenEmptybox)\fC [inline]\fP"

.SS "void ShowWidgets::SetPosScanPackage (int TposScanPackage)\fC [inline]\fP"

.SS "void ShowWidgets::SetPosSetting (int TposSetting)\fC [inline]\fP"

.SS "void ShowWidgets::SetPosSettingSystem (int TposSettingSystem)\fC [inline]\fP"

.SS "void ShowWidgets::SetPosShowPackageBox (int TposShowPackageBox)\fC [inline]\fP"

.SS "void ShowWidgets::SetPosSQLite_Local_DatabaseManager (int TposSQLite_Local_DatabaseManager)\fC [inline]\fP"

.SS "void ShowWidgets::SetPosStowPackages (int TposStowPackage)\fC [inline]\fP"

.SS "void ShowWidgets::SetStackedWidget (QStackedWidget * stackedW)\fC [inline]\fP"

.SS "void ShowWidgets::ShowWBoxChoice ()"

.SS "void ShowWidgets::ShowWConsoleWindows ()"

.SS "void ShowWidgets::ShowWCustomer ()"

.SS "void ShowWidgets::ShowWDeliveryConfirm ()"

.SS "void ShowWidgets::ShowWDoorsManager ()"

.SS "void ShowWidgets::ShowWEditSettingSystem ()"

.SS "void ShowWidgets::ShowWLogin ()"

.SS "void ShowWidgets::ShowWMaintenanceMenu ()"

.SS "void ShowWidgets::ShowWMenuDelivery ()"

.SS "void ShowWidgets::ShowWOpenEmptyBox ()"

.SS "void ShowWidgets::ShowWPackageBox ()"

.SS "void ShowWidgets::ShowWScanPackage ()"

.SS "void ShowWidgets::ShowWSetting ()"

.SS "void ShowWidgets::ShowWSettingSystem ()"

.SS "void ShowWidgets::ShowWSQLite_Local_DatabaseManager ()"

.SS "void ShowWidgets::ShowWStowPackages ()"


.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Locker_Control à partir du code source\&.
