.TH "S:/QT_CREATOR/Locker_Control/sqlite_local_databasemanager.h" 3 "Vendredi 8 Mai 2015" "Version 1.2.2" "Locker_Control" \" -*- nroff -*-
.ad l
.nh
.SH NAME
S:/QT_CREATOR/Locker_Control/sqlite_local_databasemanager.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <QWidget>\fP
.br
\fC#include <QTimer>\fP
.br
\fC#include 'showwidgets\&.h'\fP
.br
\fC#include 'csqlite_local_db\&.h'\fP
.br
\fC#include 'thread_databasemanager\&.h'\fP
.br
\fC#include 'thread_localdatabase_autosave\&.h'\fP
.br
\fC#include 'consolewindows\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSQLite_Local_DatabaseManager\fP"
.br
.RI "\fIclasse \fBSQLite_Local_DatabaseManager\fP, gestion de des actions et interractions entre l'interface de maintenance de la base de données et la classe \fBCSQLite_Local_DB\fP\&. \fP"
.in -1c
.SS "Espaces de nommage"

.in +1c
.ti -1c
.RI " \fBUi\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBWINDEX_DB_MANAGER\fP   0"
.br
.ti -1c
.RI "#define \fBWINDEX_LOADING\fP   1"
.br
.ti -1c
.RI "#define \fBWINDEX_CONFIRM\fP   2"
.br
.ti -1c
.RI "#define \fBCBINDEX_DB_LAST_SAVE\fP   0"
.br
.ti -1c
.RI "#define \fBCBINDEX_DB_DEFAULT_EMPTY\fP   1"
.br
.ti -1c
.RI "#define \fBCBINDEX_DB_DEFAULT_TEST\fP   2"
.br
.ti -1c
.RI "#define \fBEND_LOADING_TIMEOUT_SECONDS\fP   5"
.br
.ti -1c
.RI "#define \fBAUTOSAVE_DATABASE_TIMEOUT_SECONDS\fP   900"
.br
.in -1c
.SH "Documentation des macros"
.PP 
.SS "#define AUTOSAVE_DATABASE_TIMEOUT_SECONDS   900"

.SS "#define CBINDEX_DB_DEFAULT_EMPTY   1"

.SS "#define CBINDEX_DB_DEFAULT_TEST   2"

.SS "#define CBINDEX_DB_LAST_SAVE   0"

.SS "#define END_LOADING_TIMEOUT_SECONDS   5"

.SS "#define WINDEX_CONFIRM   2"

.SS "#define WINDEX_DB_MANAGER   0"

.SS "#define WINDEX_LOADING   1"

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Locker_Control à partir du code source\&.
