.TH "StowPackages" 3 "Vendredi 8 Mai 2015" "Version 1.2.2" "Locker_Control" \" -*- nroff -*-
.ad l
.nh
.SH NAME
StowPackages \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <stowpackages\&.h>\fP
.PP
Est dérivée de QWidget\&.
.SS "Connecteurs publics"

.in +1c
.ti -1c
.RI "void \fBReceiveListPackageBox\fP (QList< \fBstruct_PackagesUseBox\fP > listPackagebox)"
.br
.ti -1c
.RI "void \fBShowDeliveryConfirm\fP ()"
.br
.ti -1c
.RI "void \fBStatusDoors\fP (\fBstruct_DoorsStatus\fP doorstatus)"
.br
.ti -1c
.RI "void \fBOpenDoor\fP (int door)"
.br
.ti -1c
.RI "void \fBShowStowP\fP ()"
.br
.ti -1c
.RI "void \fBShowChangeBox\fP ()"
.br
.ti -1c
.RI "void \fBStoragePackagesFinised\fP ()"
.br
.ti -1c
.RI "void \fBSaveBoxSelected\fP ()"
.br
.in -1c
.SS "Signaux"

.in +1c
.ti -1c
.RI "void \fBSendListPackageBox\fP (QList< \fBstruct_PackagesUseBox\fP >)"
.br
.ti -1c
.RI "void \fBShowDeliveryC\fP ()"
.br
.in -1c
.SS "Fonctions membres publiques"

.in +1c
.ti -1c
.RI "\fBStowPackages\fP (\fBScanPackage\fP *WScanPackage, \fBBoxChoice\fP *WBoxChoice, \fBCSQLite_Local_DB\fP *DB, \fBCDoors\fP *doors, QWidget *parent=0)"
.br
.ti -1c
.RI "void \fBSetShowWidgets\fP (\fBShowWidgets\fP *TShowWidgets)"
.br
.ti -1c
.RI "\fB~StowPackages\fP ()"
.br
.ti -1c
.RI "void \fBResetAttribut\fP ()"
.br
.ti -1c
.RI "void \fBCreateListBoxTreeWidget\fP ()"
.br
.ti -1c
.RI "void \fBretranslateUi\fP ()"
.br
.ti -1c
.RI "void \fBAddItemListBox\fP ()"
.br
.ti -1c
.RI "void \fBUpdateBD\fP ()"
.br
.ti -1c
.RI "void \fBShowMessageError\fP (QString mesg)"
.br
.in -1c
.SH "Documentation des constructeurs et destructeur"
.PP 
.SS "StowPackages::StowPackages (\fBScanPackage\fP * WScanPackage, \fBBoxChoice\fP * WBoxChoice, \fBCSQLite_Local_DB\fP * DB, \fBCDoors\fP * doors, QWidget * parent = \fC0\fP)\fC [explicit]\fP"

.SS "StowPackages::~StowPackages ()"

.SH "Documentation des fonctions membres"
.PP 
.SS "void StowPackages::AddItemListBox ()"

.SS "void StowPackages::CreateListBoxTreeWidget ()"

.SS "void StowPackages::OpenDoor (int door)\fC [slot]\fP"

.SS "void StowPackages::ReceiveListPackageBox (QList< \fBstruct_PackagesUseBox\fP > listPackagebox)\fC [slot]\fP"

.SS "void StowPackages::ResetAttribut ()"

.SS "void StowPackages::retranslateUi ()"

.SS "void StowPackages::SaveBoxSelected ()\fC [slot]\fP"

.SS "void StowPackages::SendListPackageBox (QList< \fBstruct_PackagesUseBox\fP >)\fC [signal]\fP"

.SS "void StowPackages::SetShowWidgets (\fBShowWidgets\fP * TShowWidgets)\fC [inline]\fP"

.SS "void StowPackages::ShowChangeBox ()\fC [slot]\fP"

.SS "void StowPackages::ShowDeliveryC ()\fC [signal]\fP"

.SS "void StowPackages::ShowDeliveryConfirm ()\fC [slot]\fP"

.SS "void StowPackages::ShowMessageError (QString mesg)"

.SS "void StowPackages::ShowStowP ()\fC [slot]\fP"

.SS "void StowPackages::StatusDoors (\fBstruct_DoorsStatus\fP doorstatus)\fC [slot]\fP"

.SS "void StowPackages::StoragePackagesFinised ()\fC [slot]\fP"

.SS "void StowPackages::UpdateBD ()"


.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Locker_Control à partir du code source\&.
