.TH "struct_Database_Contains" 3 "Vendredi 8 Mai 2015" "Version 1.2.2" "Locker_Control" \" -*- nroff -*-
.ad l
.nh
.SH NAME
struct_Database_Contains \- Structure de donnée de l'application LC, utilisée pour l'enregistrement et lectures des fichiers de sauvegarde\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <DataStructures\&.h>\fP
.SS "Attributs publics"

.in +1c
.ti -1c
.RI "QString \fBTable\fP"
.br
.ti -1c
.RI "QList< QString > \fBValues\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
Structure de donnée de l'application LC, utilisée pour l'enregistrement et lectures des fichiers de sauvegarde\&. 
.SH "Documentation des données membres"
.PP 
.SS "QString struct_Database_Contains::Table"
Nom de la table dans la base de données 
.SS "QList<QString> struct_Database_Contains::Values"
Liste des lignes contenant les valeurs de champs de la table 

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Locker_Control à partir du code source\&.
