.TH "struct_PackagesUseBox" 3 "Vendredi 8 Mai 2015" "Version 1.2.2" "Locker_Control" \" -*- nroff -*-
.ad l
.nh
.SH NAME
struct_PackagesUseBox \- Structure de donnée de l'application LC, utilisée pour l'enregistrement des livraisons avec le contenu des consignes\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <DataStructures\&.h>\fP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBstruct_BoxContainment\fP"
.br
.RI "\fIStructure de donnée de l'application LC, inclus dans une 'struct_PackagesUseBox' utilisée pour renseigner le contenu des consignes\&. \fP"
.in -1c
.SS "Attributs publics"

.in +1c
.ti -1c
.RI "int \fBBoxNumber\fP"
.br
.ti -1c
.RI "struct \fBstruct_PackagesUseBox::struct_BoxContainment\fP \fBBoxContainment\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
Structure de donnée de l'application LC, utilisée pour l'enregistrement des livraisons avec le contenu des consignes\&. 
.SH "Documentation des données membres"
.PP 
.SS "struct \fBstruct_PackagesUseBox::struct_BoxContainment\fP struct_PackagesUseBox::BoxContainment"

.SS "int struct_PackagesUseBox::BoxNumber"
Identifiant de la consigne 

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Locker_Control à partir du code source\&.
