.TH "Thread_LocalDatabase_AutoSave" 3 "Vendredi 8 Mai 2015" "Version 1.2.2" "Locker_Control" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Thread_LocalDatabase_AutoSave \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <thread_localdatabase_autosave\&.h>\fP
.PP
Est dérivée de QThread\&.
.SS "Connecteurs publics"

.in +1c
.ti -1c
.RI "void \fBStartThread_LocalDatabase_AutoSave\fP ()"
.br
.in -1c
.SS "Signaux"

.in +1c
.ti -1c
.RI "void \fBTerminedThread_LocalDatabase_AutoSave\fP (bool ThreadExitValue)"
.br
.in -1c
.SS "Fonctions membres publiques"

.in +1c
.ti -1c
.RI "\fBThread_LocalDatabase_AutoSave\fP (\fBSQLite_Local_DatabaseManager\fP *parent=0, \fBCSQLite_Local_DB\fP *BD=NULL)"
.br
.ti -1c
.RI "void \fBrun\fP ()"
.br
.ti -1c
.RI "\fB~Thread_LocalDatabase_AutoSave\fP ()"
.br
.in -1c
.SH "Documentation des constructeurs et destructeur"
.PP 
.SS "Thread_LocalDatabase_AutoSave::Thread_LocalDatabase_AutoSave (\fBSQLite_Local_DatabaseManager\fP * parent = \fC0\fP, \fBCSQLite_Local_DB\fP * BD = \fCNULL\fP)\fC [explicit]\fP"

.SS "Thread_LocalDatabase_AutoSave::~Thread_LocalDatabase_AutoSave ()"

.SH "Documentation des fonctions membres"
.PP 
.SS "void Thread_LocalDatabase_AutoSave::run ()"

.SS "void Thread_LocalDatabase_AutoSave::StartThread_LocalDatabase_AutoSave ()\fC [slot]\fP"

.SS "void Thread_LocalDatabase_AutoSave::TerminedThread_LocalDatabase_AutoSave (bool ThreadExitValue)\fC [signal]\fP"


.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Locker_Control à partir du code source\&.
