.TH "Thread_StatusDoors" 3 "Vendredi 8 Mai 2015" "Version 1.2.2" "Locker_Control" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Thread_StatusDoors \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <thread_statusdoors\&.h>\fP
.PP
Est dérivée de QThread\&.
.SS "Signaux"

.in +1c
.ti -1c
.RI "void \fBStatuDoor\fP (struct \fBstruct_DoorsStatus\fP)"
.br
.in -1c
.SS "Fonctions membres publiques"

.in +1c
.ti -1c
.RI "\fBThread_StatusDoors\fP (\fBCDoors\fP *Cdoors)"
.br
.ti -1c
.RI "\fB~Thread_StatusDoors\fP ()"
.br
.ti -1c
.RI "void \fBsetListBox\fP (QList< int > list)"
.br
.ti -1c
.RI "void \fBstopThread\fP ()"
.br
.ti -1c
.RI "void \fBrun\fP ()"
.br
.in -1c
.SH "Documentation des constructeurs et destructeur"
.PP 
.SS "Thread_StatusDoors::Thread_StatusDoors (\fBCDoors\fP * Cdoors)"

.SS "Thread_StatusDoors::~Thread_StatusDoors ()"

.SH "Documentation des fonctions membres"
.PP 
.SS "void Thread_StatusDoors::run ()"

.SS "void Thread_StatusDoors::setListBox (QList< int > list)"

.SS "void Thread_StatusDoors::StatuDoor (struct \fBstruct_DoorsStatus\fP)\fC [signal]\fP"

.SS "void Thread_StatusDoors::stopThread ()"


.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Locker_Control à partir du code source\&.
