@startuml


 autonumber
 ConsoleWindows -> CSQLite_Local_DB : CSQLite_Local_DB()
 activate CSQLite_Local_DB #0000FF

 CSQLite_Local_DB -> CSQLite_Local_DB : Connect_DB()
 activate CSQLite_Local_DB #00BBFF

 database LC_SQLite_DB
 CSQLite_Local_DB -> LC_SQLite_DB : Try to connect, else\n build a new database.
 activate LC_SQLite_DB #50EEFF

 LC_SQLite_DB --> CSQLite_Local_DB : Database status (bool).
 deactivate LC_SQLite_DB

 deactivate CSQLite_Local_DB
 deactivate CSQLite_Local_DB

 CSQLite_Local_DB --> ConsoleWindows : Database satuts (bool).
 deactivate ConsoleWindows

@enduml
