@startuml


autonumber
ConsoleWindows -> CSQLite_Local_DB : DeleteExtractCode()

 alt Database is ready

     database LC_Database
     CSQLite_Local_DB -> LC_Database: SQL_Query(SELECT idBox)
     CSQLite_Local_DB -> LC_Database: SQL_Query(SELECT idPackage)
     CSQLite_Local_DB -> LC_Database: SQL_Query(DELETE ExtractCode)

     loop idPackage
          CSQLite_Local_DB -> LC_Database: SQL_Query(DELETE idPackage)
          loop idBox
               CSQLite_Local_DB -> LC_Database: SQL_Query(UPDATE Box)
          end
     end

     alt Delete success
         CSQLite_Local_DB -> ConsoleWindows : true deleted
     else
         CSQLite_Local_DB -> ConsoleWindows : false no delete
     end

 else
     CSQLite_Local_DB -> ConsoleWindows : false no database connection
 end
@enduml
