@startuml


QThread <|-- Thread_Databasemanager

Thread_Databasemanager *-- SQLite_Local_DatabaseManager
SQLite_Local_DatabaseManager o-- Thread_Databasemanager

CSQLite_Local_DB o-- Thread_Databasemanager

Thread_Databasemanager  o-- SQLite_Local_DatabaseManager

@enduml
